FROM openjdk:21-slim

RUN groupadd -r minecraft && useradd -r -g minecraft minecraft

WORKDIR /data
RUN mkdir -p /data/plugins

COPY paper-1.21.11.jar /data/
COPY ../build/*.jar /data/plugins/

RUN chown -R minecraft:minecraft /data

USER minecraft

EXPOSE 25565

CMD echo "eula=true" > /data/eula.txt && \
    java -Xmx2G -Xms2G -jar /data/paper-1.21.11.jar nogui